### ISSUE TITLE
Reduce complexity of entry function?

### ISSUE THREAD

**Issue by brainstorm** [ramonmarrero/aws-cdk-r-container#2]
Hello again,

While working with your code, I noticed that you use 3 different R files to launch R lambdas...

At first I was a bit puzzled by the contents of `bootstrap.R`:

```R
source('/var/task/runtime.R')
# TODO: Why the multiple initializeRuntime()?
tryCatch({
    function_name <- initializeRuntime()
    while (TRUE) {
        handle_request(function_name)
        logReset()
        rm(list=ls())
        source('/var/task/runtime.R')
        function_name <- initializeRuntime()
    }
}, error = throwInitError)
```

Could you please elaborate on why are there multiple `initializeRuntime()` and the use of the `while(TRUE)`? Did you face some operational issues if you didn't do it this way?

In my mind, `runtime.R` is appropriate to bundle some utility functions but I'm a bit confused by the code above and why not include the custom code/function into `bootstrap.R` itself instead of having `functions.R`?

Also, how would you expand your example to accept incoming parameters such handling S3 events?

**Comment by brainstorm** [comment]
Another tangential reason I'm asking for further improvements is that I'd love to see this [being benchmarked sometime in the future alongside other runtimes](https://filia-aleks.medium.com/benchmarking-all-aws-lambda-runtimes-in-2021-cold-start-part-1-e4146fe89385) and so we need something we can easily [compare against with (as apples-to-apples as possible)](https://github.com/Aleksandr-Filichkin/aws-lambda-runtimes-performance) ;)

**Comment by ramonmarrero** [comment]
I have provided a fix. 

source('/var/task/runtime.R')
tryCatch({
    function_name <- initializeRuntime()
    handle_request(function_name)
    logReset()
    rm(list=ls())
}, error = throwInitError)

**Comment by brainstorm** [comment]
Cool, thanks for https://github.com/ramonmarrero/aws-cdk-r-container/commit/3200f53bf5bd296b6beff0be78216f8b1a1a713d#diff-8561c57431eac0cea855106ada4e3fd50075bbd6d5fd8e19c21d603a1920a754 !
